<?php

/*********************************************************************
* Extension configuration file for ext "esp".
*
* Generated by ext 29-07-2015 15:33 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'user' => 't3elmar',
  'comment' => 'Try to enable automatic PDF rendering on docs.typo3.org',
  'title' => 'esp - Call Stored Procedures from TypoScript',
  'description' => '
Back to speed!	
-- Model: Roaring fast MySQL Stored Procedures, View: Good old TypoScript. -- A fast alternative to Extbase. 
-- Ships the classes SimpleRenderer for single table queries and JoinRenderer for joined table queries. 
-- You can easily add your own renderer classes for special tasks. Just implement the method render() like seen in SimpleRenderer or JoinRenderer.
',
  'category' => 'misc',
  'version' => '6.2.4',
  'state' => 'beta',
  'uploadfolder' => false,
  'createDirs' => '',
  'clearcacheonload' => true,
  'author' => 'Elmar Hinz',
  'author_email' => 't3elmar@gmail.com',
  'author_company' => 'Elmar Hinz',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.1.0-6.2.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
);

?>
